### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by sjyoo**
"f" caused invalid syntax error

### CODE REVIEW

**Comment by wwj718** [comment]
Thanks for your PR!
It is [f-strings](https://www.python.org/dev/peps/pep-0498/) syntax,  require `python >= 3.6`.
I will adjust [the Vector document](https://adapter.codelab.club/extension_guide/vector/)
Thanks!

**Comment by sjyoo** [comment]
FYI, I have errors on Python 3.6 and 3.7

```
(vector2) :~/codelab_adapter/servers$ python --version
Python 3.6.10 :: Anaconda, Inc.
```

**Comment by wwj718** [comment]
This problem may be caused by the [PYTHON3_PATH](https://adapter.codelab.club/user_guide/settings/#python3_path)， 

Please set your Python path(`which python`) to PYTHON3_PATH(`~/codelab_adapter/user_settings.py`)

**Comment by wwj718** [comment]
Hi @sjyoo ，Adapter has been upgraded to 3.2, do you still have the problem?

**Pull request closed without merging**
